var quotes = 
[
    '"I am bound to this world by the strongest chain of them all - Student debts" - Jack Corvus',
    '"everyone is a sack of meat, some just do it better" - nanika',
    '"whaaaat, these guys dont agree with me? fokin anti free speech assholes" - Jack Corvus',
    '"well that was quicker than my sex life" - Ronin',
    '"Random thought. What if the polar ice caps arent melting because of global warming, less ozone, etc. But because someone just put a buncha r7 1800 @ 6ghz in there .3. Well, iirc the guy that got it to that clock uses like liquid nitrogen and it still got to 40-60c." - Jack Corvus',
    '"when I want porn but all I find is memes" - Demo',
    '"stop stealing my favorite pair of panties" - Bushwomann',
    '"Were all having a gay ol time" - Bierb',
    '"Wtf help call the ambulance ghosts kicking my ball" - Julius',
    '"If i wanna get spooked, Ill just do something that makes my mom calls my full name" - Jack Corvus',
    '"You overestimate the space of movement for dicks" - Bierb',
    '"And my dick isnt terrifying" - BloodsAndTears',
    '"I am now going to proceed to pleasure myself with this fish" - Bierb',
    '"Im gonna marry my hands, adopt cats and call them my kids." - BloodsAndTears',
    '"Daddy Max, Daddy Marty is actig weird again." - BloodsAndTears',
    '"so are we fucking her or not because if not im gonna go eat breakfast" - Azimuth',
    '"Maybe anakin hated sand because it IS indeed gay" - Bierb',
    '"We have you, thats enough gay for all of us." - Marty',
    '"Jek brek the snek" - Athener',
    '"Max apperently wants to give birth to tiny sneks through his nipples" - FenFen and HatHat',
    '"yall prego with nipple sneks now" - FenFen and HatHat',
    '"Not even kidding he paid like 50 Euros for something barely resembling suicide in burger shape and he ate it all" - Demo',
    '"Imagine a guy goes to the train station to kill himself by jumping in front of the train but on the way there he gets hit by a truck." - Demo',
    '"Buildings dont fly as quickly as indonesians" - Bierb',
    '"Bears are just fat dogs" - Bierb',
    '"To prevent death you gotta prevent life. So if you use condoms you prevent death. So be a life saviour and use condoms." - Marty    ',
    '"I feel like if men can detach their dicks, hed do that and ship it to me." - BloodsAndTears',
    '"The only thing making you better than Donald Duck is spawncamping." - Marty',
    '"Just need to saw my penis in half so I can bend enough to suck my own spine." - Marty',
    '"My favourite word as a kid was ´Ombelom´." - Demo',
    '"do not question the logic of it, for there is none" - Jack Corvus',
    '"DONT :clap~1: CALL :clap~1: YOUR :clap~1: SELF :clap~1: BISEXUAL :clap~1: IF :clap~1: YOUVE :clap~1: NEVER :clap~1: FUCKED :clap~1: A :clap~1: BICYCLE" -Demo',
    '"Im too afraid to look up "neko fantasy" without "discrete" in the search bar, Im too pure for that." - Lilin',
    '"What have we learned from Nekos Sky? Procedurally generated nekos are boring." - Marty',
    '"Wroom wroom why am I an engie?" - Lilin',
    '"Mutated Nekro-Neko-Panic-Milk (war. Mutated Nekro-Neko-Panic-Milk (war never changes." - Lilin',
    '"ITS JUST AN ASS SLAPPING SIM OH MY GOD This. is. perfect." - Flakket',
    '"Im going to suicide oops wrong chat" - DavidTR',
    '"Ganz ehrlich, deine ganzen Bra-Witze sind so schlecht... die kannst du BHlten!!!!! :D:D:D:D:" - Lilin',
    '"Honestly, your bra-jokes are so terrible... BRAEEP THEM!!! :D:D:D:D: [Sadly, this joke is absolutely incoherent in English.]" - also Lilin    ',
    '"If loving Pots is gay, I dont wanna be straight. Im gay as fuck." - Black Mass',
    '"30 minutes until I obtain the bread" - Marty',
    '"Hey. Imagine if girls didnt have dicks" - Demo',
    '"this is why parents need to beat their kids." - Pingusader',
    '"why are we doing research about yiff" - CallMeSnort',
    '"Your anus will be resized by a mod" - Pearl',
    '"Can I haz b e e s e c h u r g e r" - Demo',
    '"Hummon is gay and should go die" - amyzie',
    '"Hitler was a pretty good guy" - tomkiel',
    '"imagine ricardo fusing with bepis man" - Marty',
    '"YOU JUST TOUCHED MY SANDVICH" - Superflys girlfriend',
    '"ALSO HE DOESNT EAT ASS" - potsu',
    '"Yes, yeet me like one of your nekos" - YakuzaGirl',
    '"Dont die yet, youve yet to yeet me" - YakuzaGirl',
    '"i wanna be stereotype german but I cant find any cyanide" - Marty',
    '"thank u for ur support. im proud to announce i am now have pp" - potsu',
    '"its cool how teh entire trans community is one hive mind" - Nirwanda',
    '"No girls allowed in my treehouse" - Demo',
    '"Ill yeet you harder than my dick gets when I see neko ecchi" - Marty',
    '"I dont kiss ppl whomstdvest dick i sucked" - Marty',
    '"You wouldnt download a car" - Cactus',
    '"Being human is a terrible thing to be." - SigmaWolf',
    '"that oughta be one of the best noses Ive ever seen" - Marty',
    '"this hurts my penis bone structure" - Marty',
    '"oh god weve reached 1 yeet" - mixomin',
    '"you can shut your filthy whore mouth bm" - potsu',
    '"Help us defeat Faggot-Chan in the reactions !" - Lincroyable homme tabouret',
    '"The chair cant freeze, ma brudda!"- DuckingAGoose',
    '"The ceiling is uwu" - Jack Corvus',
    '"Shes my cock scabbard" - KAP',
    '"Ima cock smack all their foreheads" - sourpeach',
    '"you damn europeans tryna take away my guns" - Fustuv',
    '"put your cat ears on my dicky owo owo" - Super Huenchen',
    '"gonna go to mcd and order a macInvertebrates and a extra larj creepy crawly cola" - hejhog',
    '"whats a borb I want to know borb. Hi borb" - BuddhaLicious',
    '"i bought my own house this year and got two new puppies and death still sounds gucci" - Becca',
    '"as if there already isnt Superfly hentai" - mixomin',
    '"hentai is just anime with more juice" - Princess Hazylina',
    '"I will squirt mayo on your toes" - Becca',
    '"If you Think about it, love can Stop a woman from bleeding for atleast sometime too" - Princess Hazylina',
    '"I dont say I hate you. I say Id rather get fricked in my butt with a steel dildo by a rabid monkey than be associated with you." - hejhog',
    '"i never thought id see the sentence "unzips bone", yet here we are" - HellReaper',
    '"i am heteroshreksuel" - Marty',
    '"that word gave me a stroke" - HellReaper',
    '"Nah, Id still would rather suck a dick than licking whatever floppy mess a girls got between her legs :BLARGH:" - Rocky',
    '"that gif makes me want to sexually assault a bird" - HellReaper',
    '"IM JUST TRYING TO BE HIP WITH ALL THE """"COOL KIDS"""" NOWADAYS! :ElmAngry: By fucking them and be a dad with my 10 yo husbando:chika: :chika: :chika:" - Rocky',
    '"son,im gonna blow that dumb cock right off your stupid balls" - HellReaper',
    '"Hitler was an incel je. Topkek" - HellReaper',
    '"How to get a gf: Just fck a bitch and create one. ez" - Rocky',
    '"i do speak diabeetus infused space being" - Marty',
    '"mir steckt leider n schwanz im popo ich kann leider nicht kommen" - whoever is at lucys',
    '"like, if you look like a dude, and someone saw you do something suspicious, and said "what is he doing", would you break down and cry" - UnnamedBeast',
    '"u massive omegacuck" - Marty',
    '"i love how demo made a sjw rule and now we are like the most turbofags ever" - Marty',
    '"wheres my trap porn" - Nitodes',
    '"wait shit I joined a german chat. fuck" - Mr.Phoenix',
    '"damn this server finally is the shithole i love" - Marty',
    '"u hurt my feelings. and i dont even have any feelings" - sarah',
    '"we took a break to regenerate our limbs" - Marty',
    '"astolfo is my spirit animal" - Marty',
    '"Is this some sort of a german orgy and marty deep throated too hard?" - DuckyTheLucky',
    '"dick sucking is overrated" - Nitodes',
    '"I wonder how many reichs do you need for the ideology to work" - DuckyTheLucky',
    '"after all, were all a fucking faggot orgy server full of love and braincell loss" - Marty',
    '"bruh he go "pshhhh" and now that rocket aint yours no more" - mixomin',
    '".o< quack >o." - Xeon',
    '"if youre a necrophile and find him hot, hes dead" - Marty',
    '"welp, i look like a viking who got kidnapped by retarded brits when i turned 14 and wsa forced to adopt to victorian age english people culture" - Marty',
    '"i know a dildo when i see one" - Marty',
    '"skin color is a hoax created by the government to sell more racism" - Marty',
    '"im so fat, even if i was drawn in 2d id be 3d" - Marty',
    '"you only weeb if your bodypillow can walk bcs its so full of cum!" - Marty',
    '"do gay people aknowledge the existence of oatmeal?" - Adam mickiewicz',
    '"So people can stop dying now? Unfortunate" - (Ivan)',
    '"dude if loreknight didnt dm me bcs of my excessive language youd be in for a lingual asswhooping of multiversional dimensions" - Marty',
    '"theyre just sentence enhancers smh" - Marty',
    '"The reason the devs arent with TF2 anymore are because Marty scared them away with their butt" - SushiBot',
    '"you could recreate the holocaust with that roast" - Marty',
    '"true gamers take their moms virginity" - Marty',
    '"i am still just a fish in a condom" - 404UNF',
    '"What is this shitpostery" - 404UNF',
    '"do you celebrate valentines with your left hand or right hand" - Ded',
    '"Sorry Im not a cross eyed broken tooth fuckin brexit fag" - Mika',
    '"he deathed" - boki',
    '"pyro is firegender. pronouns are mmph/hhmph" - Dax',
    '"only thing that happens rn is elliot rodger talking about driving a train into a kitten orphanage.... aint anything wild here" - Marty',
    '"you see the bullet going underneath the trumpet" - Wimmer',
    '"Haha, now you have penis haircut" - Jim Lahey',
    '"why would you cut off your balls" - Odyssey346',
    '"Also, theres a fuckin peanut somewhere inside my hoodie"- Jim Lahey',
    '"Drug the headpats" - SMM',
    '"Also my dick is probably so numb from fappin so hard I would feel lips on it. So Ill go with tight butt" - Rocky',
    '"the enemy of my enemy can suck my dick" - Marty',
    '"Fried headcrab mukbang :yum:" - Mass',
    '"you cum, I sniff" - Mass',
    '"i prefer chicken butthole" - Deletion',
    '"i shit myself when ever i eat peanut butter" - moldy',
    '"If update is out then Ill become femboy and stream on twitch to show my thicc femboy thighs" - Roy',
    '"i made myself into a chicken mcnugget and ate myself. funnies shit ive ever seen" - Marty',
    '"man i was mad with you and you somehow turned things around and got me horny" - Doctor. Andron',
    '"like, i am not even joking, its 2020, grow up, science has been replaced by essential oils, who gives a fuck about genes" - Marty',
    '"If a man is not free to fart in his own house, is he free at all?" - TexasSkyV3',
    '"collectors mad milk is just scout being an omegaincel and storing cum for 2 years before releasing it in his collectors brony jar to create collectors mad milk" - Marty',
    '"wait whos out here buying poop" - chillcookiedough',
    '"christ came back but died from polio bcs his mother was antivaxx" - Marty',
    '"oh yes I love halving my internet speed while using a shared IP that someones used to download 500TB of interracial midget porn on" - JonathanTF',
    '"just use the bread from expiration date as a fleshlight" - Marty',
    '"WE MUST FIND THE INVERTED BREAD" - Classic HWG',
    '"Im crusading in 21th century. Im mastermind of bruh" - Strelok',
    '"FOCUS ON BEING A FUCKING CAT" - Jon Arbuckle',
    '"the first 6 times, only me and the boys.... then one day, me and the boys and one girl.... and boy was he simping.... like, i think his simping radiated so hard into the core of the world that soon we will have planet earth wear a fedora and trying to bang the moon." - Marty',
    '"One day one man on a one toilet dropped the biggest turd in the human history without even knowing about it"- Jaxter',
    '"i trained my ass muscles specifically for operating a meatgrinder" - Marty',
    '"my dick just became self concious" - Marty',
    '"ERP with furry pyro mains for keys" - Moth',
    '"minion girl penis" - Moth',
    '"lesbians fondle balls in attempt to purchase liver" - Moth',
    '"Imagine his pc freeze and all he sees is fucking big smoke eating cj ass" - turbo',
    '"2 gays in the bouncy castle" - Kumpir',
    '"julius ceaser started as a salad" - SneakyDingus',
    '"vore is like communism" - Roy',
    '"subjectively speaking, i am objectively correct" - Suilla',
    '"I dont have 2 dicks!!!" - Drace',
    '"All will fear the tri-willy bi horde" - ChorusHM',
    '"oi mate u bloddy wot mate swer on me mum ill proper bang yu innit" - engineer gaming',
    '"titty skittles" - Pyroshi',
    '"real chads do backend management while being plowed into the fucking matress" - steph',
    '"Dicks and asses go hand in hand" - 404UNF',
    '"*aggresively owo`s*" - Sev',
	'"Why would you milk Scout" - Sev',
	'"Mmmmmm yeah baby show me that geometry" - Jack Corvus',
    '"i am personally going to shove a grilled cucumber up the ass of the MVM staging servers" - ZoNiCaL',
    '"i do NOT want to be daddy" - Twilight Sparkle',
    '"looking thru pp now" - colonel',
    '"JUDY HOOPS IS GREGAGANT" - Julia Burger',
    '"THE LEFT WANTS YOUR COCK" - Chlorondria',
    '"mf keeps throwing eggs in my aquarium" - eggfuckerMC',
    '"*sucks your dick with malicious intent*" - Astriel',
    '"Luce. Dont fuck the water NodeFilter. u3u" - Lou',
    '"His asshole looks like it can accept both coins and credit" - Lou',
    '"im not sticking a dick in my nostril" - hermit crab',
    '"How is chess homophobic when the queens try to diddle each other the whole game" - Kumpir',
    '"anyway time to listen to cocks" - Moonly Days',
    '"ok, thats too much effort to watch german dubbed minecraft porn" - PanMann'
]

function newQuote() 
{
    var randomNumber = Math.floor(Math.random() * (quotes.length));
    document.getElementById('quoteDisplay').innerHTML = quotes[randomNumber];
}
